name: Python Test and Push

on: [push]  # Trigger the workflow on push events

jobs:
  test-and-push:
    runs-on: ubuntu-latest  # Specify the runner environment

    steps:
      - uses: actions/checkout@v3  # Check out the code
      - name: Set up Python  # Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with your desired version
      - name: Run tests  # Run your Python tests
        run: echo "Hello" > file.txt
      - name: Push changes on success  # Push changes if tests pass
        if: success()
        run: |
          git config --local user.email "fhaya420@gmail.com"
          git config --local user.name "Shinystar128"
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push
